### PR TITLE
Fix for JBEE-172: Unable to find unambiguous method: class java.lang.String.replace(java.lang.String, java.lang.String)

### PR DESCRIPTION
**Pull request by fesaab**
Hi, 

After some search I found that the fix for [JBEE-172](https://issues.jboss.org/browse/JBEE-172) was already done on Tomcat 7:
* bug [56425](https://bz.apache.org/bugzilla/show_bug.cgi?id=56425)
* commit [66642e9ca0674b13843b72e202593e3e58fc2894](https://github.com/apache/tomcat/commit/66642e9ca0674b13843b72e202593e3e58fc2894) 

As the code base has changed a bit I took the changes of the above commit and applied to JBoss EL API Spec too.

I validated the fix on WildFly 9.0.2.Final + JSF 1.2.

I'm requesting this merge because I believe this fix is worth for the new releases as well.

Thanks in advance.

### CODE REVIEW

**Comment by dmlloyd** [comment]
We require that all contributions be made under the terms of the MIT License, http://www.opensource.org/licenses/mit-license.php. Do you agree to the these terms?

**Comment by fesaab** [comment]
Yes, I agree.

**Comment by fjuma** [comment]
@fesaab Thanks for working on this. It looks good, just have a couple comments:

- Please squash your commits into a single commit.
- Please reference JBEE-172 in your commit message.

**Comment by fesaab** [comment]
Done @fjuma !

**Review by fjuma — APPROVED** [review]

**Pull request merged**
