### PR TITLE
WFLY-5882: "Implemented" var arg invocations.

### PR DESCRIPTION
**Pull request by wolfc**
https://issues.jboss.org/browse/WFLY-5882

### CODE REVIEW

**Comment by ctomc** [comment]
@wolfc this change is against master, but bug was reported against 2.2 branch.
Is fix the same?

**Comment by scottmarlow** [comment]
https://github.com/jboss/jboss-el-api_spec/issues/17 mentions that no upstream is needed.

**Comment by scottmarlow** [comment]
Also, I don't see a ELUtil.java on master

**Comment by scottmarlow** [comment]
Looks like upstream ELUtil needs the varargs patch applied to me.

**Comment by scottmarlow** [comment]
merged and deployed snapshot 1.0.6.Final-20160311.025734-5

**Pull request closed without merging**
